export const THEME = {
    BACKGROUND_COLOR: '#000',
    COMPONENT_BACKGROUND_COLOR: '#252525',
    TEXT_COLOR: '#fff',

    NAVIGATION_BUTTON_ACTIVE_COLOR: '#ffc400',
    NAVIGATION_BUTTON_INACTIVE_COLOR: '#646464',
    BUTTON_BLUE_COLOR: '#00DBD3',
}
