export const userData = [
    {
        id: '1',
        img: require('../assets/photos/Александр_Москвин.jpg'),
        name: 'Александр',
        surname: 'Москвин',
        sales: 2356,
    },
    {
        id: '2',
        img: require('../assets/photos/Евгения_Мартынова.jpg'),
        name: 'Евгения',
        surname: 'Мартынова',
        sales: 2456,
    },
    {
        id: '3',
        img: require('../assets/photos/Елена_Вавилова.jpg'),
        name: 'Елена',
        surname: 'Вавилова',
        sales: 1561,
    },
    {
        id: '4',
        img: require('../assets/photos/Ольга_Мальцева.jpg'),
        name: 'Ольга',
        surname: 'Мальцева',
        sales: 2215,
    },
    {
        id: '5',
        img: require('../assets/photos/Григорий_Комаров.jpg'),
        name: 'Григорий',
        surname: 'Комаров',
        sales: 1850,
    },
    {
        id: '6',
        img: require('../assets/photos/Валерий_Тимошин.jpg'),
        name: 'Валерий',
        surname: 'Тимошин',
        sales: 1056,
    },
    {
        id: '7',
        img: require('../assets/photos/Марина_Добронравова.jpg'),
        name: 'Марина',
        surname: 'Добронравова',
        sales: 984,
    },
    {
        id: '8',
        img: require('../assets/photos/Оксана_Синицина.jpg'),
        name: 'Оксана',
        surname: 'Синицина',
        sales: 514,
    },
    {
        id: '9',
        img: require('../assets/photos/Софья_Захаренко.jpg'),
        name: 'Софья',
        surname: 'Захаренко',
        sales: 745,
    },
    {
        id: '10',
        img: require('../assets/photos/Татьяна_Анисимова.jpg'),
        name: 'Татьяна',
        surname: 'Анисимова',
        sales: 1238,
    },
]
