export const userData = [
    {
        id: '1',
        img: '../assets/photos/Александр Москвин.jpg',
        name: 'Александр',
        surname: 'Москвин',
        sales: 2356,
    },
    {
        id: '2',
        img: '../assets/photos/Евгения Мартынова.jpg',
        name: 'Евгения',
        surname: 'Мартынова',
        sales: 2456,
    },
    {
        id: '3',
        img: '../assets/photos/Елена Вавилова.jpg',
        name: 'Елена',
        surname: 'Вавилова',
        sales: 1561,
    },
    {
        id: '4',
        img: '../assets/photos/Ольга Мальцева.jpg',
        name: 'Ольга',
        surname: 'Мальцева',
        sales: 2215,
    },
    {
        id: '5',
        img: '../assets/photos/Григорий Комаров.jpg',
        name: 'Григорий',
        surname: 'Комаров',
        sales: 1850,
    },
    {
        id: '6',
        img: '../assets/photos/Валерий Тимошин.jpg',
        name: 'Валерий',
        surname: 'Тимошин',
        sales: 1056,
    },
    {
        id: '7',
        img: '../assets/photos/Марина Добронравова.jpg',
        name: 'Марина',
        surname: 'Добронравова',
        sales: 984,
    },
    {
        id: '8',
        img: '../assets/photos/Оксана Синицина.jpg',
        name: 'Оксана',
        surname: 'Синицина',
        sales: 514,
    },
    {
        id: '9',
        img: '../assets/photos/Софья Захаренко.jpg',
        name: 'Софья',
        surname: 'Захаренко',
        sales: 745,
    },
    {
        id: '10',
        img: '../assets/photos/Татьяна Анисимова.jpg',
        name: 'Татьяна',
        surname: 'Анисимова',
        sales: 1238,
    },
]
